### ISSUE TITLE
Minor optimization in Python code

### ISSUE THREAD

**Issue by MichaelDeutschCoding** [nayuki/Reference-Huffman-coding#12]
In `huffmancoding.py` the CodeTree class builds the tree [using tuples as the prefix](https://github.com/nayuki/Reference-Huffman-coding/blob/a74553c299cc18146886ab3e3b778b393c50192d/python/huffmancoding.py#L214C1-L214C66). I suspected that using a string might be more efficient, so I did some checks. While tuples and strings are both immutable, but it turns out that there's a huge difference in memory consumption for tuples over strings. It's not such significant differences at lower sizes, but at any length greater than 1 a string does have a smaller footprint.

The following short script demonstrates the difference both in memory usage and timing.
```python
from sys import getsizeof
from timeit import timeit


def compare_size(length):
    s = "1" * length
    t = tuple((1,) * length)
    str_size = getsizeof(s)
    tuple_size = getsizeof(t)
    diff = tuple_size - str_size
    print(f"{length:3}  string size: {str_size:3}  tuple size: {tuple_size:4}  diff: {diff:4}")

def compare_sizes():
    print("\n\t~~~ SIZE COMPARISONS ~~~")
    for i in range(11):
        compare_size(i)

    for i in range(50, 501, 50):
        compare_size(i)


def mutating_tuple():
    t = ()
    for _ in range(100):
        t += (1,)
    return t

def mutating_str():
    s = ""
    for _ in range(100):
        s += "1"
    return s

def compare_times():
    print("\n\t~~~ TIME COMPARISONS ~~~")    
    repetitions = 100_000
    str_time = timeit(mutating_str, number=repetitions)
    tuple_time = timeit(mutating_tuple, number=repetitions)
    print(f"Repetitions: {repetitions},  string took: {str_time},  tuple took: {tuple_time}")


compare_sizes()
compare_times()
``` 

Results on my computer were the following:
```
	~~~ SIZE COMPARISONS ~~~
  0  string size:  49  tuple size:   40  diff:   -9
  1  string size:  50  tuple size:   48  diff:   -2
  2  string size:  51  tuple size:   56  diff:    5
  3  string size:  52  tuple size:   64  diff:   12
  4  string size:  53  tuple size:   72  diff:   19
  5  string size:  54  tuple size:   80  diff:   26
  6  string size:  55  tuple size:   88  diff:   33
  7  string size:  56  tuple size:   96  diff:   40
  8  string size:  57  tuple size:  104  diff:   47
  9  string size:  58  tuple size:  112  diff:   54
 10  string size:  59  tuple size:  120  diff:   61
 50  string size:  99  tuple size:  440  diff:  341
100  string size: 149  tuple size:  840  diff:  691
150  string size: 199  tuple size: 1240  diff: 1041
200  string size: 249  tuple size: 1640  diff: 1391
250  string size: 299  tuple size: 2040  diff: 1741
300  string size: 349  tuple size: 2440  diff: 2091
350  string size: 399  tuple size: 2840  diff: 2441
400  string size: 449  tuple size: 3240  diff: 2791
450  string size: 499  tuple size: 3640  diff: 3141
500  string size: 549  tuple size: 4040  diff: 3491

	~~~ TIME COMPARISONS ~~~
Repetitions: 100000,  string took: 0.40804569981992245,  tuple took: 2.178954300004989
``` 

I'm happy to submit a small PR with this change if you'd like. Thanks for your great repo! I learned a lot looking through it 👍

**Comment by nayuki** [comment]
Thanks for all your work in this. Glad to hear you learned something - that's why it's marketed as a reference implementation. I really appreciate the thorough explanations and test code you provided. I went ahead and fixed the typo in the comment.

The size difference you're seeing is because each string character bumps up the memory requirement by 1 byte, whereas each tuple member bumps it by one pointer which is 8 bytes on a 64-bit system, because a tuple element can be any arbitrary object (not just an integer). If you want to learn more about this aspect, it helps to study low-level languages like assembly, C, and C++, and really understand how stacks, heaps, and structs work. (I see that your repositories consist mostly of Python code, with a bit of C#.)

There are several reasons why I am rejecting this change:

* My project [web page](https://www.nayuki.io/page/reference-huffman-coding) says: "This project is a clear implementation of Huffman coding, suitable as a reference for educational purposes. [...] The code can be used for study, and as a solid basis for modification and extension. Consequently, the codebase optimizes for readability and avoids fancy logic, and does not target the best speed/memory/performance."

* Using and passing around strings as a data structure type is considered an anti-pattern. For example, joining a first name and space and and last name is considered inferior to having a proper struct that has two separate strings. There are many pages on this subject: [0](https://wiki.c2.com/?StringlyTyped), [1](https://www.techopedia.com/definition/31876/stringly-typed), [2](https://devcards.io/stringly-typed), [3](https://cocoacasts.com/the-danger-of-string-literals-and-stringly-typed-code), [4](https://cocoacasts.com/code-smells-in-swift-stringly-typed-code), [5](https://www.google.com/search?q=stringly+typed).

* Changing the Python port to use strings will desynchronize from the Java and C++ ports, which use lists of integers.

* Huffman coding is essentially always used on a binary output alphabet, but it can be [extended to higher bases](https://en.wikipedia.org/wiki/Huffman_coding#n-ary_Huffman_coding). In that case, your stringly typed approach will fail if there are more than 10 output symbols, whereas my existing integer approach will work for any alphabet size.
