### ISSUE TITLE
Modifying how files are read.

### ISSUE THREAD

**Issue by allanbz** [nayuki/Reference-Huffman-coding#4]
Hello. I am a Brazilian student of Computer Engineering, currently in the third semester. First, sorry to mess with your code, it was perfect the way it was, however, one of my programming teachers launched a challenge for the class: find and modify an open source Java project.

So I found your project and found it very intuitive and educational, so I took the liberty of modifying it just as a way of learning (they call it refactoring, if I'm correct).

I did not modify anything other than reading the files and a comment that was just above the main class in HuffmanCompress.java and HuffmanDecompress.java that referred to the previous read mode, and you have no obligation to merge. The files I created are called "(Alternative)HuffmanCompress.java" and "(Alternative)HuffmanDecompress.java".

I just wanted to say a big Thank You for indirectly helping me and for making me learn some new tricks in Java.

P.S. Sorry for  my English, it's not my first language haha ;D
P.S.². If I did something wrong, could you tell me? A feedback would be greatly appreciated *-*

**Comment by nayuki** [comment]
Hi Allan, thank you for acknowledging the nature of your code contribution. I understand that you were compelled to make changes to an open-source codebase as a part of course work.

What you did is not called refactoring. It is a general change of adding or modifying features. Refactoring specifically refers to changing internal names and structures **without** any change in visible behavior.

You don't have to tell me what you modified or didn't modify. I read commit diffs carefully to make sure no change slips by undetected. You're welcome for finding my Huffman coding project useful! It is designed for educational use in mind, and you are the perfect audience.

Since you asked about anything done wrong, I will spare no detail:

* Your English is just fine. It can pass as native, and needs no apologizing for.
* You opened 2 pull requests and 3 issues. You should have opened only 1 pull request and included the explanation as a comment.
* Your 2 pull requests were on the same topic and should have been combined into 1. You should have added both classes at the same time.
* The changes you made, adding the Scanner and prompt strings, are perfectly appropriate for private projects but I feel are inappropriate for this reference material. I find that prompt strings or other aspects of human-computer interaction design are too influenced by stylistic choice and there is hardly one right answer. So I chose to deliberately avoid prompt strings, and force the user to use command line arguments. This is quite the standard design for Unix tools.

**Comment by allanbz** [comment]
Thanks for the feedback and thanks again for the help. I'll think carefully about the facts you've pointed out, and try to improve my skills and the way I use Git.

Keep up the good work, and you can be sure that you are helping a lot of people.
